name : Deploy lambda

on:
  push:
    branches:
     - main

jobs:
  deploy:

    name: deploy to aws
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14.x

    strategy:
      matrix:
        python-version:
          - 3.8
    
    steps:
      - uses : actions/checkout@v2
      - name : Set Up Python ${{ matrix.python-version }}
        uses : actions/setup-python@v2
        with :
          python-version : ${{ matrix.python-version }}
      
      - name : cache pip
        uses : actions/cache@v2
        with :
          path : ~/.cache/pip
          key : ${{ runner.os }}-pip-${{hashFiles('requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name : Install dependency 
        run : |
              python -m pip install --upgrade pip
              python -m venv venv
              source venv/bin/activate
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          mkdir deployment-package
          cp -r venv/lib/python3.8/site-packages/* deployment-package/
          cp -r * deployment-package/
          cd deployment-package
          zip -r ../lambda-deployment-package.zip .
          
      - name : default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: barkote_send_sms
          zip_file: lambda-deployment-package.zip   
     